# Generated by Django 4.2 on 2023-04-27 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hall_base",
            options={"verbose_name": "放映厅", "verbose_name_plural": "放映厅"},
        ),
        migrations.AlterModelOptions(
            name="movie_base",
            options={"verbose_name": "电影", "verbose_name_plural": "电影"},
        ),
        migrations.AlterModelOptions(
            name="session_base",
            options={"verbose_name": "场次", "verbose_name_plural": "场次"},
        ),
        migrations.AlterModelOptions(
            name="ticket_base",
            options={"verbose_name": "票", "verbose_name_plural": "票"},
        ),
        migrations.AddField(
            model_name="movie_base",
            name="views",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="访问量"
            ),
        ),
        migrations.AddField(
            model_name="ticket_base",
            name="status",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="状态"
            ),
        ),
        migrations.AddField(
            model_name="ticket_base",
            name="time_create",
            field=models.DateTimeField(
                default=django.utils.timezone.now, max_length=20, verbose_name="下单时间"
            ),
        ),
    ]
