# Generated by Django 4.2 on 2023-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "productApp",
            "0002_alter_hall_base_options_alter_movie_base_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_base",
            name="seat",
            field=models.IntegerField(blank=True, null=True, verbose_name="座号"),
        ),
    ]
