# Generated by Django 4.2 on 2023-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0003_alter_ticket_base_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_base",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[(-1, "已取消"), (0, "未生效"), (1, "待核销"), (2, "已核销")],
                default=0,
                null=True,
                verbose_name="状态",
            ),
        ),
    ]
