# Generated by Django 4.2 on 2023-05-05 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("productApp", "0004_alter_ticket_base_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_base",
            name="session",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productApp.session_base",
                verbose_name="场次",
            ),
        ),
        migrations.AlterField(
            model_name="ticket_base",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
