# Generated by Django 4.2 on 2023-05-05 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0005_alter_ticket_base_session_alter_ticket_base_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="kind_base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.TextField(max_length=50)),
            ],
            options={"verbose_name": "类型", "verbose_name_plural": "类型",},
        ),
        migrations.AddField(
            model_name="movie_base",
            name="rate",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="评分"
            ),
        ),
        migrations.AlterField(
            model_name="movie_base",
            name="time_publish",
            field=models.DateField(
                default=datetime.date(2023, 5, 5), max_length=20, verbose_name="上映时间"
            ),
        ),
        migrations.CreateModel(
            name="picture_base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="剧照", max_length=50)),
                ("pic", models.ImageField(upload_to="movie/")),
                (
                    "movie",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productApp.movie_base",
                        verbose_name="场次",
                    ),
                ),
            ],
            options={"verbose_name": "剧照", "verbose_name_plural": "剧照",},
        ),
    ]
