# Generated by Django 4.2 on 2023-05-05 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0006_kind_base_movie_base_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie_base",
            name="time_publish",
            field=models.DateField(
                default=django.utils.timezone.now, max_length=20, verbose_name="上映时间"
            ),
        ),
    ]
