# Generated by Django 4.2 on 2023-05-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0007_alter_movie_base_time_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie_base",
            name="label",
            field=models.ManyToManyField(
                default=None, null=True, to="productApp.kind_base", verbose_name="标签"
            ),
        ),
        migrations.AlterField(
            model_name="picture_base",
            name="movie",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productApp.movie_base",
                verbose_name="场次",
            ),
        ),
        migrations.AlterField(
            model_name="ticket_base",
            name="session",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="productApp.session_base",
                verbose_name="场次",
            ),
        ),
    ]
