# Generated by Django 4.2 on 2023-05-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0008_movie_base_label_alter_picture_base_movie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture_base",
            name="movie",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pictures",
                to="productApp.movie_base",
                verbose_name="场次",
            ),
        ),
    ]
