# Generated by Django 4.2 on 2023-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0010_alter_movie_base_name_alter_picture_base_movie_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="product_data",),
        migrations.AlterField(
            model_name="hall_base",
            name="name",
            field=models.CharField(max_length=100, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="movie_base",
            name="name",
            field=models.CharField(max_length=100, verbose_name="名称"),
        ),
    ]
