# Generated by Django 4.2 on 2023-05-08 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("productApp", "0011_delete_product_data_alter_hall_base_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie_base",
            name="rate",
            field=models.FloatField(
                blank=True, default=5.0, null=True, verbose_name="评分"
            ),
        ),
        migrations.CreateModel(
            name="review_base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("head", models.CharField(default="标题", max_length=50)),
                (
                    "mark",
                    models.FloatField(
                        blank=True, default=5.0, null=True, verbose_name="评分"
                    ),
                ),
                ("body", models.TextField(max_length=500, verbose_name="内容")),
                (
                    "movie",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productApp.movie_base",
                        verbose_name="电影",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "短评", "verbose_name_plural": "短评",},
        ),
    ]
