# Generated by Django 4.2 on 2023-05-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0012_alter_movie_base_rate_review_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kind_base", name="kind", field=models.CharField(max_length=50),
        ),
    ]
