# Generated by Django 4.2 on 2023-05-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0014_alter_review_base_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="jumbotron_base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.ImageField(upload_to="jumbotron/")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jumbotron",
                        to="productApp.movie_base",
                        verbose_name="电影",
                    ),
                ),
            ],
            options={"verbose_name": "海报", "verbose_name_plural": "海报",},
        ),
    ]
