# Generated by Django 4.2 on 2023-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0016_alter_jumbotron_base_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jumbotron_base",
            name="pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="jumbotron/"
            ),
        ),
    ]
