# Generated by Django 4.2 on 2023-05-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("productApp", "0018_alter_ticket_base_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_exp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, default=None, upload_to="user/"),
                ),
                (
                    "favorite",
                    models.ManyToManyField(
                        default=None,
                        null=True,
                        to="productApp.movie_base",
                        verbose_name="想看",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
