# Generated by Django 4.2 on 2023-05-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0019_user_exp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_exp",
            name="favorite",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                to="productApp.movie_base",
                verbose_name="想看",
            ),
        ),
    ]
