# Generated by Django 4.2 on 2023-05-22 17:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("productApp", "0021_review_base_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_exp",
            name="photo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="static/img/default.jpg",
                upload_to="user/",
                verbose_name="头像",
            ),
        ),
    ]
