# Generated by Django 4.2.1 on 2023-05-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0022_alter_user_exp_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_base',
            name='last_seats',
        ),
        migrations.AddField(
            model_name='session_base',
            name='ordered_seats',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已订座位数'),
        ),
    ]
